### PR TITLE
adds previewTemplate option to override the default preview template

### PR DESCRIPTION
**Pull request by jsalva**
http://www.dropzonejs.com/#config-previewTemplate

### CODE REVIEW

**Comment by jsalva** [comment]
I added a few commits to optionally exclude the dropzone css, which I didn't want to use (and was interfering with my custom css).

It'll use it by default now, but you can optionally disable it (see README)

**Comment by jvsidler** [comment]
+1

**Comment by kcollignon** [comment]
+1

**Comment by FutoRicky** [comment]
Nice

**Pull request merged**
